version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - C:/Users/winte/.aws:/root/.aws:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
