name: Deploy FastAPI on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            if [ ! -d fastapi-llm-agent ]; then
              git clone https://github.com/${{ github.repository }} fastapi-llm-agent
            fi
            cd fastapi-llm-agent
            git fetch origin
            git reset --hard origin/main

            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

            docker-compose down --remove-orphans
            docker-compose pull || true
            docker-compose build --no-cache
            docker-compose up -d
          EOF
